version: '3.11'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    image: app:app
    container_name: media_markt_saturn_container
    command: python manage.py runserver 0.0.0.0:8000