name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT : development
      SECRET_KEY : secret_key
      ENCRYPT_KEY : epgMRl-KNNO1F6RmPHHmW5aTUX6HH1afLCqj9TbiVqw=

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.3

      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      
    #   - name: Run migrations
    #     run: python manage.py migrate
      
      - name: Run Tests
        run: python manage.py test